name: "Publish Chart"

on:
  pull_request:
    paths:
      - .github/workflows/publish_chart.yml
      - chart/**
  push:
    paths:
      - .github/workflows/publish_chart.yml
      - chart/**
    branches:
      - main

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Create Chart Package
        run: helm package chart -d ./tmp

      - name: Login to Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | helm registry login ${{ vars.REGISTRY_ADDR }} --username ${{ vars.REGISTRY_USERNAME }} --password-stdin

      - name: Login to Registry, ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - name: Push Packaged Chart to Registry
        run: helm push ./tmp/* oci://${{ vars.REGISTRY_ADDR }}/library

      - name: Push Packaged Chart to Registry, ghcr.io
        run: helm push ./tmp/* oci://ghcr.io/${{ github.repository_owner }}/chart
